CREATE DATABASE PetCircle;

USE PetCircle;


CREATE TABLE Users (
    UserId INT PRIMARY KEY AUTO_INCREMENT,
    FullName VARCHAR(100) NOT NULL,
    Password VARCHAR(100) NOT NULL,
    PhoneNumber VARCHAR(100) NOT NULL,
    NickName VARCHAR(100) NOT NULL,
    Img LONGBLOB NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Status INT NOT NULL,
    CreationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Categories (
    CategoryId INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL UNIQUE,
    Description VARCHAR(100),
    Status INT NOT NULL
);

CREATE TABLE Posts (
    PostId INT PRIMARY KEY AUTO_INCREMENT,
    UserId INT NOT NULL,
    CategoryId INT NOT NULL,
    Title VARCHAR(100) NOT NULL,
    Description VARCHAR(200) NOT NULL,
    CreationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Status INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(UserId),
    FOREIGN KEY (CategoryId) REFERENCES Categories(CategoryId)
);

CREATE TABLE Images (
	ImgId INT PRIMARY KEY AUTO_INCREMENT,
    PostId INT NOT NULL,
    Img LONGBLOB NOT NULL,
    FOREIGN KEY (PostId) REFERENCES Posts(PostId)
);

CREATE TABLE Files (
	FileId INT PRIMARY KEY AUTO_INCREMENT,
    PostId INT NOT NULL,
    File LONGBLOB NOT NULL,
    FOREIGN KEY (PostId) REFERENCES Posts(PostId)
);
